### ISSUE TITLE
ModuleNotFoundError: No module named '__main__.cronController'; '__main__' is not a package

### ISSUE THREAD

**Issue by dev-mtshikomba** [blavejr/OrganiseDesktop#92]
`D:\OrganiseDesktop-master\OrganiseDesktop-master
(env) λ python organise_desktop\Clean.py
Traceback (most recent call last):
  File "organise_desktop\Clean.py", line 4, in <module>
    from .cronController import  schedule_end, schedule_start
ModuleNotFoundError: No module named '__main__.cronController'; '__main__' is not a package

D:\OrganiseDesktop-master\OrganiseDesktop-master
(env) λ cd organise_desktop\

D:\OrganiseDesktop-master\OrganiseDesktop-master\organise_desktop
(env) λ python Clean.py
Traceback (most recent call last):
  File "Clean.py", line 4, in <module>
    from .cronController import  schedule_end, schedule_start
ModuleNotFoundError: No module named '__main__.cronController'; '__main__' is not a package
`

**Comment by blavejr** [comment]
Hey @dev-mtshikomba, could you let me know which OS you are running on?

**Comment by KokoseiJ** [comment]
I'd assume Windows, judging from his CWD.

While I currently can't access my PC for, 2 more days, I think your environment could be the culprit. Are you sure that you have cronController.py in the same folder where Clean.py is?

**Comment by shashank1623** [comment]
The `python -m organise_desktop` cmd works to solve the problem of relative import
